"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var b2bCandidateDetailsPO_1 = require("../PO/b2bCandidateDetailsPO");
var RandomStringGeneratorUtil_1 = require("../Util/RandomStringGeneratorUtil");
var waitStatementUtil_1 = require("../Util/waitStatementUtil");
var selectUtil_1 = require("../Util/selectUtil");
var b2bCandidateDetailsLib = /** @class */ (function () {
    function b2bCandidateDetailsLib() {
    }
    b2bCandidateDetailsLib.prototype.candidateDetails = function () {
        var firstName = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(6);
        var lastName = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(6);
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.firstNameTxtBx.sendKeys(firstName);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.lastNameTxtBx.sendKeys(lastName);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.dobDayTxtBx.sendKeys(RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.dateOfBirth(1, 28));
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bBirthMonth = new selectUtil_1.selectUtil(b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.dobMonthDrpBx);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bBirthMonth.selectByIndex(5);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.dobYearTxtBx.clear();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.dobYearTxtBx.sendKeys(RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.dateOfBirth(1988, 1995));
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.genderBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bIdentityDropdwn = new selectUtil_1.selectUtil(b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.identificationDocDrpBx);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bIdentityDropdwn.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.identificationDocNumberTxBx.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var identityDocumentNumber = RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.getRandomString(6);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.identificationDocNumberTxBx.sendKeys(identityDocumentNumber);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.expdateDayTxtBx.sendKeys(RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.dateOfBirth(1, 28));
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bIdentityExpiry = new selectUtil_1.selectUtil(b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.expdateMonthDrpBx);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bIdentityExpiry.selectByIndex(5);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.expdateYearTxtBx.sendKeys(RandomStringGeneratorUtil_1.RandomStringGeneratorUtil.dateOfBirth(2035, 2045));
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.nxtBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        var Selb2bqualificationLevel = new selectUtil_1.selectUtil(b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.qualLevelDrpBx);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        Selb2bqualificationLevel.selectByIndex(2);
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.selectExamSearchBx.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.inputExamSearchValueTxtBx.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.inputExamSearchValueTxtBx1.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.examTypeRadioBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait1();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.pickSelectedexmBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait2();
        b2bCandidateDetailsPO_1.b2bCandidateDetailsPO.addExmBtn.click();
        waitStatementUtil_1.waitStatementUtil.customWait2();
    };
    return b2bCandidateDetailsLib;
}());
exports.b2bCandidateDetailsLib = b2bCandidateDetailsLib;
